version: '2.28'

services:
  api:
    build: ./Api-Tcc
    ports:
      - "8080:8080"
    environment:
          - TZ=America/Sao_Paulo
    networks:
      - clinic-network
networks:
  clinic-network:
    driver: bridge
